### PR TITLE
Remove unused iCub3 hand configuration files

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/icub-models/issues/105 .

### CODE REVIEW

**Comment by traversaro** [comment]
Apparently the script requires some modification to properly deal with "removal" of generated files.

**Comment by Nicogene** [comment]
I missed this PR sorry! Is it ready to be merged @traversaro ?

**Review by Nicogene — APPROVED** [review]
LGTM

**Comment by traversaro** [comment]
I do not remember well to be honest.

**Comment by traversaro** [comment]
I checked now the PR and it seems to me ready to be merged, the files that I Wanted to remove to avoid confusion were modified in https://github.com/robotology/icub-models-generator/pull/212, however it seems to me that it still make sense to just remove them.

**Comment by Nicogene** [comment]
> I checked now the PR and it seems to me ready to be merged, the files that I Wanted to remove to avoid confusion were modified in #212, however it seems to me that it still make sense to just remove them, what do you think @Nicogene ?

Yes go ahead

**Comment by traversaro** [comment]
I do not have the time to fix the conflict at this time. Let's close and reopen in the future.

**Pull request closed without merging**
