### PR TITLE
Tune the PID controller on iCubGazeboV3 and remove not used files

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR changes some gains of iCubGazeboV3. Thanks to that gains I was able to improve the walking performances.

Furthermore, I also remove some files that seem not to be used.

cc @Nicogene and @traversaro

### CODE REVIEW

**Review by Nicogene — CHANGES_REQUESTED** [review]
Ok for me, except for the removal of the left/right_arm.ini files, you are right they are not used right now, but one day we will add the hands, then we will them, thanks!

**Comment by traversaro** [comment]
> you are right they are not used right now, but one day we will add the hands, then we will need them, thanks!

When we will them, we can add them, right? 
Otherwise in the meantime it is highly error prone to have files that we do not update and nobody is testing at all, so they could accumulate errors over time. If we ever need to see those files, we just need to go back to them (git remembers).

**Comment by traversaro** [comment]
Even when we add the hands, probably it would make sense to have one single file that we use in both cases, rather then duplicate information over different configuration files.

**Review by Nicogene — APPROVED** [review]
> When we will them, we can add them, right?
Otherwise in the meantime it is highly error prone to have files that we do not update and nobody is testing at all, so they could accumulate errors over time. If we ever need to see those files, we just need to go back to them (git remembers).

Yes sure, it was not a strong constraint for me, we can proceed merging

**Comment by traversaro** [comment]
To clarify, I was the one that suggested to @GiulioRomualdi to delete the files, hence my explanation.

**Pull request merged**
