### PR TITLE
Delete iCub directory of icub-models every time the models are re-generated

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/robotology/icub-models/issues/185 . 

Blocked by https://github.com/robotology/icub-models/pull/186 .

### CODE REVIEW

**Comment by traversaro** [comment]
I added a few prints in the CI to check before merging, and this PR will delete the following files as they are not generated anymore by icub-model-generator apparently:
~~~
 	deleted:    iCub/conf/FT/gazebo_icub_left_foot_front_ft.ini
	deleted:    iCub/conf/FT/gazebo_icub_left_foot_rear_ft.ini
	deleted:    iCub/conf/FT/gazebo_icub_right_foot_front_ft.ini
	deleted:    iCub/conf/FT/gazebo_icub_right_foot_rear_ft.ini
	deleted:    iCub/conf/gazebo_icub_head.ini
	deleted:    iCub/conf/gazebo_icub_left_arm.ini
	deleted:    iCub/conf/gazebo_icub_left_arm_no_forearm.ini
	deleted:    iCub/conf/gazebo_icub_left_arm_no_hand.ini
	deleted:    iCub/conf/gazebo_icub_left_hand.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_finger.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_fingers.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_index.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_mais.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_middle.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_pinky.ini
	deleted:    iCub/conf/gazebo_icub_left_hand_thumb.ini
	deleted:    iCub/conf/gazebo_icub_right_arm.ini
	deleted:    iCub/conf/gazebo_icub_right_arm_no_forearm.ini
	deleted:    iCub/conf/gazebo_icub_right_arm_no_hand.ini
	deleted:    iCub/conf/gazebo_icub_right_hand.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_finger.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_fingers.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_index.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_mais.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_middle.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_pinky.ini
	deleted:    iCub/conf/gazebo_icub_right_hand_thumb.ini
	deleted:    iCub/conf_icub3/MTB/gazebo_icub_left_arm_mtb.ini
	deleted:    iCub/conf_icub3/MTB/gazebo_icub_left_leg_mtb.ini
	deleted:    iCub/conf_icub3/MTB/gazebo_icub_right_arm_mtb.ini
	deleted:    iCub/conf_icub3/MTB/gazebo_icub_right_leg_mtb.ini
	deleted:    iCub/conf_icub3/MTB/gazebo_icub_torso_mtb.ini
	deleted:    iCub/conf_icub3/gazebo_icub_head.ini
	deleted:    iCub/conf_icub3/gazebo_icub_head_without_eyes.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_arm.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_arm_no_forearm.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_arm_no_hand.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_finger.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_fingers.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_index.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_mais.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_middle.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_pinky.ini
	deleted:    iCub/conf_icub3/gazebo_icub_left_hand_thumb.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_arm.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_arm_no_forearm.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_arm_no_hand.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_finger.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_fingers.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_index.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_mais.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_middle.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_pinky.ini
	deleted:    iCub/conf_icub3/gazebo_icub_right_hand_thumb.ini
	deleted:    iCub/conf_icub3/gazebo_icub_robotname.ini
	deleted:    iCub/conf_icub3/gazebo_icub_xsens_inertial.ini
	deleted:    iCub/conf_icub3/left_camera.ini
	deleted:    iCub/conf_icub3/right_camera.ini
	deleted:    iCub/conf_icub3/yarpmotorgui.ini
	deleted:    iCub/meshes/simmechanics/sim_icub3_head_prt.stl
	deleted:    iCub/meshes/simmechanics/sim_icub3_neck_1_prt.stl
	deleted:    iCub/meshes/simmechanics/sim_icub3_neck_2_prt.stl
	deleted:    iCub/meshes/simmechanics/sim_icub3_neck_3_prt.stl
~~~

More and less, it seems to me that they are similar to the list provided by @xEnVrE in https://github.com/robotology/icub-models/issues/185 . If some files are actually needed, we should add them in `icub-model-generator` . @mebbaid @Nicogene do you think there is some file we still need?

**Comment by mebbaid** [comment]
> do you think there is some file we still need?

@traversaro  currently the `iCubGazeboV3_visuomanip` urdf refernce the following two files out of the list
- iCub/conf_icub3/gazebo_icub_left_arm.ini
- iCub/conf_icub3/gazebo_icub_right_arm.ini

It is perhaps not necessary, and in case we can change the urdf to reference an automatically generated one.

**Comment by traversaro** [comment]
Good catch @mebbaid ! Probably we can move those files in https://github.com/robotology/icub-models/tree/master/iCub_manual/conf_manual/iCubGazeboV3_visuomanip ?

**Comment by mebbaid** [comment]
> Good catch @mebbaid ! Probably we can move those files in https://github.com/robotology/icub-models/tree/master/iCub_manual/conf_manual/iCubGazeboV3_visuomanip ?

yeah, it seems ok to me.

**Review by Nicogene — APPROVED** [review]
I had a similar issue in [`ergocub-software`](https://github.com/icub-tech-iit/ergocub-software), probably I have to implement something similar also there, right now I am doing manual cleanups.

**Comment by traversaro** [comment]
@mebbaid @Nicogene can we proceed in merging this PR?

**Comment by Nicogene** [comment]
I would say yes!

**Comment by mebbaid** [comment]
It's a go for me as well.

**Pull request merged**
