### PR TITLE
fixing URDF for left- and right-foot-skin

### PR DESCRIPTION
**Pull request by simeonedussoni**
as per [this issue](https://github.com/robotology/icub-main/issues/899) I swapped the corresponding reference frame coordinates to align the URDF to the actual hardware and skingui configuration

### CODE REVIEW

**Comment by traversaro** [comment]
Sorry, I need to have a table to check to double check the changes, based on the info on https://github.com/robotology/icub-main/issues/899 :

| Wrong ID (before)  | Correct ID (after) |
|:------------------:|:------------------:|
|  3  |  15   |
|  4  |  0    |
|  2  |  14   |
|  1  |  11    |
|  12  |  12   |
|  13  |  1    |
|  8   |  2    |
|  9   |  3    |
|  10  |  4    |
|  11  |  14   |
|  14  |  8  |
|  15  |  9   |
|  0   | 10   | 

So, the frame of CORRECT ID should get the position that before was of Wrong ID.

The changes seems correct, but I have a few doubts regarding this PR for @simeonedussoni :
* the issue https://github.com/robotology/icub-main/issues/899 reports the mismatch on the left sole, is the mapping on the right sole the same?
* the issue https://github.com/robotology/icub-main/issues/899 reports the mismatch on the left sole, but this PR only modifies the right sole, there is any reason for this?
* If also the image in https://github.com/robotology/icub-main/blob/master/app/skinGui/iniGenerators/left_foot_ini_generator.xlsx is wrong, shouldn't we also either remove or change that?

I also had another doubt, that anyhow is not directly related to this PR. It seems that all the `SCSYS_*_FOOT_SKIN_*` and `*_foot_skin_*`  frames share the same orientation. However, I tought that without an orientation it is not possible to orient the triangles and localize correctly the single taxel in 3D. However, checking the code to visualize the taxel positions in https://gitlab.fel.cvut.cz/body-schema/icub/icub-skin-calibration/-/blob/main/skin_models/skin_from_urdf.py#L34 does not use the orientation from the URDF and in https://github.com/robotology/icub-models-generator/blob/master/simmechanics/scripts/generate_taxels_3d_positions.py#L339, apparently the orientation from the .ini is the one used to orient the triangles.

**Comment by simeonedussoni** [comment]
> orientation

concerning the orientation, I also had this doubt. but if the orientations are wrong, one should see overlapping triangles in the plot, which is not the case, so the orientation info is taken elsewhere...

I go on by correcting the left foot.

**Comment by simeonedussoni** [comment]
actually I was heavily misled by the plot which seems a right foot. I check the right foot mounting.

**Comment by simeonedussoni** [comment]
I confirm the right foot patch has the same orientation as the left foot so the modifications already made are ok.

**Comment by simeonedussoni** [comment]
modified also the left foot.

**Comment by traversaro** [comment]
Should we also update https://github.com/robotology/icub-main/blob/master/app/skinGui/iniGenerators/left_foot_ini_generator.xlsx and https://github.com/robotology/icub-main/blob/master/app/skinGui/iniGenerators/right_foot_ini_generator.xlsx ? From https://github.com/robotology/icub-main/issues/899 it seems that also the id there are wrong.

**Comment by pattacini** [comment]
I would say yes!
cc @simeonedussoni

**Comment by pattacini** [comment]
> Should we also update https://github.com/robotology/icub-main/blob/master/app/skinGui/iniGenerators/left_foot_ini_generator.xlsx and https://github.com/robotology/icub-main/blob/master/app/skinGui/iniGenerators/right_foot_ini_generator.xlsx ? From [robotology/icub-main#899](https://github.com/robotology/icub-main/issues/899) it seems that also the images with the id there are wrong.

cc @simeonedussoni

**Comment by traversaro** [comment]
FYI @simeonedussoni @pattacini do you still want to integrate this change?

**Comment by pattacini** [comment]
> FYI @simeonedussoni @pattacini do you still want to integrate this change?

Definitely!
Kind reminder for @simeonedussoni

**Comment by simeonedussoni** [comment]
I checked the file mentioned by @traversaro above. 

- left foot: it seems the file in the iniGenerator folder has the correct positions and just the picture is misaligned (that is sounding since otherwise the .ini generated should have had the uncorrect triangles placement
- right foot the same. the only misalignment is at the level of the applied labels to the picture, the positions generated are coherent with the .ini.

opened [PR in icub-main](https://github.com/robotology/icub-main/pull/912)

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Ok, thanks!

**Pull request merged**
