### PR TITLE
icub3: remove (almost) all the mass/inertia workaround

### PR DESCRIPTION
**Pull request by Nicogene**
Except the small inertia fixes and the asymmetry between `l_upperarm` and `r_upperarm` that remains an open point

The COM should be higher now because with @salvi-mattia noticed that when I put the same masses between r and l for the ankle I wrongly took the bigger one 

Here is the model

immagine

Before merging, @S-Dafarra @prashanthr05 @GiulioRomualdi could you please test the model?

cc @salvi-mattia @pattacini

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Look fine for me, but as @Nicogene mentioned a check may be a good idea.

**Comment by S-Dafarra** [comment]
That looks nice. The best thing would be testing it on the robot, but I don't feel so confident in changing it now :thinking:

**Comment by pattacini** [comment]
> I don't feel so confident in changing it now 🤔

Sure! Perhaps you could give it a run on Gazebo to start with, as a first validation step.

**Comment by S-Dafarra** [comment]
We were about to try, but I realized only now the corresponding ``urdf`` is not is ``devel`` right?

**Comment by traversaro** [comment]
> 
> 
> We were about to try, but I realized only now the corresponding `urdf` is not is `devel` right?

Not at the moment. Indeed, if @Nicogene agrees we can simply merge https://github.com/robotology/icub-models-generator/pull/194 to simplify deployment and then we do eventual new fixes as new PRs.

**Pull request merged**
