### PR TITLE
Update iDynTree to 12.3.3 and actually test FT sensor frame consistency

### PR DESCRIPTION
**Pull request by traversaro**
iDynTree 12.3.3 fixed a bug that prevented to properly test if the FT sensors were properly exported (https://github.com/robotology/idyntree/pull/1191), updating the iDynTree version should ensure that we catch https://github.com/robotology/icub-models-generator/issues/275 and ideally https://github.com/robotology/icub-models-generator/issues/271 .

### CODE REVIEW

**Comment by traversaro** [comment]
Great, apparently we were not even running test in CI, now I enabled them.

**Comment by traversaro** [comment]
Great, the tests are now failing:

˜˜˜
 ✨ Pixi task (test_generated_models in default): ctest --test-dir .build
Internal ctest changing into directory: /home/runner/work/icub-models-generator/icub-models-generator/.build
Test project /home/runner/work/icub-models-generator/icub-models-generator/.build
      Start  1: iCubGenova03ConsistencyCheck
 1/16 Test  #1: iCubGenova03ConsistencyCheck .............   Passed    0.01 sec
      Start  2: iCubNancy01ConsistencyCheck
 2/16 Test  #2: iCubNancy01ConsistencyCheck ..............   Passed    0.01 sec
      Start  3: iCubLisboa01ConsistencyCheck
 3/16 Test  #3: iCubLisboa01ConsistencyCheck .............   Passed    0.01 sec
      Start  4: iCubGazeboV2_5ConsistencyCheck
 4/16 Test  #4: iCubGazeboV2_5ConsistencyCheck ...........***Failed    0.02 sec
      Start  5: iCubGazeboV2_6ConsistencyCheck
 5/16 Test  #5: iCubGazeboV2_6ConsistencyCheck ...........***Failed    0.03 sec
      Start  6: iCubGazeboV2_7ConsistencyCheck
 6/16 Test  #6: iCubGazeboV2_7ConsistencyCheck ...........***Failed    0.02 sec
      Start  7: iCubGazeboV2_5_KIT_007ConsistencyCheck
 7/16 Test  #7: iCubGazeboV2_5_KIT_007ConsistencyCheck ...***Failed    0.02 sec
      Start  8: iCubGazeboV3ConsistencyCheck
 8/16 Test  #8: iCubGazeboV3ConsistencyCheck .............   Passed    0.01 sec
      Start  9: iCubGenova01ConsistencyCheck
 9/16 Test  #9: iCubGenova01ConsistencyCheck .............***Failed    0.02 sec
      Start 10: iCubGenova02ConsistencyCheck
10/16 Test #10: iCubGenova02ConsistencyCheck .............***Failed    0.02 sec
      Start 11: iCubGenova04ConsistencyCheck
11/16 Test #11: iCubGenova04ConsistencyCheck .............***Failed    0.02 sec
      Start 12: iCubGenova09ConsistencyCheck
12/16 Test #12: iCubGenova09ConsistencyCheck .............   Passed    0.01 sec
      Start 13: iCubGenova11ConsistencyCheck
13/16 Test #13: iCubGenova11ConsistencyCheck .............***Failed    0.02 sec
      Start 14: iCubErzelli02ConsistencyCheck
14/16 Test #14: iCubErzelli02ConsistencyCheck ............***Failed    0.02 sec
      Start 15: iCubDarmstadt01ConsistencyCheck
15/16 Test #15: iCubDarmstadt01ConsistencyCheck ..........***Failed    0.02 sec
      Start 16: iCubWaterloo01ConsistencyCheck
16/16 Test #16: iCubWaterloo01ConsistencyCheck ...........***Failed    0.02 sec

31% tests passed, 11 tests failed out of 16

Errors while running CTest
Output from these tests are in: /home/runner/work/icub-models-generator/icub-models-generator/.build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Total Test time (real) =   0.32 sec

The following tests FAILED:
	  4 - iCubGazeboV2_5ConsistencyCheck (Failed)
	  5 - iCubGazeboV2_6ConsistencyCheck (Failed)
	  6 - iCubGazeboV2_7ConsistencyCheck (Failed)
	  7 - iCubGazeboV2_5_KIT_007ConsistencyCheck (Failed)
	  9 - iCubGenova01ConsistencyCheck (Failed)
	 10 - iCubGenova02ConsistencyCheck (Failed)
	 11 - iCubGenova04ConsistencyCheck (Failed)
	 13 - iCubGenova11ConsistencyCheck (Failed)
	 14 - iCubErzelli02ConsistencyCheck (Failed)
	 15 - iCubDarmstadt01ConsistencyCheck (Failed)
	 16 - iCubWaterloo01ConsistencyCheck (Failed)
Error: Process completed with exit code 8.
˜˜˜

**Comment by traversaro** [comment]
Specific error:

```
(icub-models-generator) icub@arm64-apple-darwin20 .build % ctest -VV -R V2_7
UpdateCTestConfiguration  from :/Users/icub/src/icub-models-generator/.build/DartConfiguration.tcl
Parse Config file:/Users/icub/src/icub-models-generator/.build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/icub/src/icub-models-generator/.build/DartConfiguration.tcl
Parse Config file:/Users/icub/src/icub-models-generator/.build/DartConfiguration.tcl
Test project /Users/icub/src/icub-models-generator/.build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 6
    Start 6: iCubGazeboV2_7ConsistencyCheck

6: Test command: /Users/icub/src/icub-models-generator/.build/tests/icub-model-test "--model" "/Users/icub/src/icub-models-generator/.build/iCub/robots/iCubGazeboV2_7/model.urdf"
6: Working Directory: /Users/icub/src/icub-models-generator/.build/tests
6: Test timeout computed to be: 1500
6: icub-model-test : checkAxisDirectionsV2 test performed correctly 
6: icub-model-test : base_link test performed correctly 
6: icub-model-test : sole are parallel test performed correctly 
6: icub-model-test : checkFTSensorsAreEvenAndNotNull test performed correctly 
6: icub-model-test : model /Users/icub/src/icub-models-generator/.build/iCub/robots/iCubGazeboV2_7/model.urdf does not contain frame l_arm_ft as expected.
6: icub-model-test : model /Users/icub/src/icub-models-generator/.build/iCub/robots/iCubGazeboV2_7/model.urdf does not contain frame r_arm_ft as expected.
1/1 Test #6: iCubGazeboV2_7ConsistencyCheck ...***Failed    0.03 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
	  6 - iCubGazeboV2_7ConsistencyCheck (Failed)
```

**Comment by traversaro** [comment]
By updating to the version of simmechanics-to-urdf with the fix in https://github.com/robotology/simmechanics-to-urdf/pull/62, the test pass fine. These introduces back the frames

* `l_arm_ft` (in the same location of `l_arm_ft_imu`)
* `r_arm_ft` (in the same location of `r_arm_ft_imu`)
* `imu_frame` (in the same location of `head_imu_0`)

**Comment by traversaro** [comment]
Unfortunately, after this fix the test pass again, so we do not have useful tests to debug https://github.com/robotology/icub-models-generator/issues/271 .

**Review by martinaxgloria — APPROVED** [review]

**Review by Nicogene — APPROVED** [review]

**Pull request merged**
