### PR TITLE
Fix the colors for iCubV2_5 and iCubV3

### LINKED ISSUE #216: Investigate on how to fix the colors in the urdf models
Thanks to https://github.com/robotology/idyntree/pull/961 it will be possible to display the icub models with the colors defined in the `urdf` files.

I noticed that the robot colors are "randomly" chosen when the model is generated. As a consequence, the representation of the model is a bit bizarre

image

This is  how TALOS is loaded by the very same visualizer 

 
Do you think it's possible to fix the color of the links?

cc @traversaro

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR closes #216 and required https://github.com/robotology/simmechanics-to-urdf/pull/51 to properly work

In detail, this PR defines the colors for each link of the robots. I've chosen the color arbitrally let me know if you prefer a different palette.

After this PR and https://github.com/robotology/idyntree/pull/961 if iCub is loaded in the iDynTree visualizer we will get:

 
meshcat (1)
meshcat

# TODO
- [x] ~~Once https://github.com/robotology/simmechanics-to-urdf/pull/51  has been merged update the CI~~ Not required since the ci already get the latest commit of `simmechanics-to-urdf`

cc @robotology/iit-artificial-mechanical-intelligence @Nicogene

### CODE REVIEW

**Comment by traversaro** [comment]
The color for `iCubV2_5` seems suspisciously iCubGenova04 specific. :D 
However, for me the one that does the job decide which color to pick, so I do not see a big problem with this color. Just pinging @pattacini for a double check.

**Comment by pattacini** [comment]
>Just pinging @pattacini for a double check.

Fine with me too 👍🏻 
(although I personally dislike the iCub in red 😄 why did you choose it for iCubGenova04!)

**Review by Nicogene — APPROVED** [review]

**Comment by traversaro** [comment]
Note that all the link of the model will remain "gray" when displayed in Classic Gazebo due to https://github.com/ignitionrobotics/sdformat/pull/526#issuecomment-817895903 .

**Comment by traversaro** [comment]
https://github.com/robotology/simmechanics-to-urdf/pull/51 was merged!

**Comment by GiulioRomualdi** [comment]
Since the CI already uses the latest commit of `simmechanics-to-urdf` we can avoid to update the workflow

**Pull request merged**
