### PR TITLE
Update iCub3 with feet covers

### PR DESCRIPTION
**Pull request by mfussi66**
The purpose of this PR is to update the simulation model of iCub 3 with the new feet covers. The model is shown in the picture below. The checkout used to generate the model is `cad-mechanics-public` `master` , commit: https://github.com/icub-tech-iit/cad-mechanics-public/commit/a83def6d2299d850d0777876c39a9fa88c5b8860

image

cc @S-Dafarra @GiulioRomualdi

### CODE REVIEW

**Review by Nicogene — DISMISSED** [review]
If these changes have been tested on gazebo, green light from my side 👍🏻

**Comment by Nicogene** [comment]
But check it out that it is failing to generate the models :https://github.com/robotology/icub-models-generator/pull/210/checks?check_run_id=3676209300

**Comment by mfussi66** [comment]
@Nicogene They were not tested in Gazebo, but I can of course do it as needed.

**Comment by pattacini** [comment]
Here's one error:
```console
2021-09-22T14:21:58.9629855Z   File "/usr/local/lib/python3.8/dist-packages/simmechanics_to_urdf-0.2-py3.8.egg/simmechanics_to_urdf/firstgen.py", line 916, in buildTree
2021-09-22T14:21:58.9630992Z KeyError: ('r_ankle_2', 'SCSYS_R_ANKLE_2')
2021-09-22T14:21:58.9985516Z make[2]: *** [simmechanics/CMakeFiles/generate-models-simmechanics.dir/build.make:180: simmechanics/iCubGazeboV3.urdf] Error 1
```

cc @Mick3Lozzo

**Comment by Mick3Lozzo** [comment]
Well, I have to verify this with @mfussi66, is seems regarding the ankle, but I don't know if it is a problem of the CAD simulation model.

**Comment by pattacini** [comment]
Quoting @Mick3Lozzo 

>This coordinate system is inside a suppressed "test" group, so it is not included in the simulation model generation. Now we have SCSYS_R_ANKLE_2_FT_FRONT and SCSYS_R_ANKLE_2_FT_REAR.

I think we could remove it. Is it still used somehow in your application @GiulioRomualdi @S-Dafarra ?

**Comment by S-Dafarra** [comment]
> Quoting @Mick3Lozzo
> 
> > This coordinate system is inside a suppressed "test" group, so it is not included in the simulation model generation. Now we have SCSYS_R_ANKLE_2_FT_FRONT and SCSYS_R_ANKLE_2_FT_REAR.
> 
> I think we could remove it. Is it still used somehow in your application @GiulioRomualdi @S-Dafarra ?

I did not understand what you are referring to

**Comment by pattacini** [comment]
I'm referring to the frame `SCSYS_R_ANKLE_2`, which is causing the problem although seems to belong to the "suppressed test group" as we now have the two frames, one for the front and one for the rear soles.

**Comment by S-Dafarra** [comment]
> I'm referring to the frame `SCSYS_R_ANKLE_2`, which is causing the problem although seems to belong to the "suppressed test group" as we now have two frames, one for the front and one for the rear soles.

I don't think I ever seen it

**Comment by mfussi66** [comment]
Since it is a `KeyError`, it means that the script cannot find the key `r_ankle_2`, which of course is a consequence of the reference frame not being present in the model (aka the XML generated file). So I think that it means that I have to remove the instances of `r_ankle_2` in the file `ICUB_3_all_options.yaml`, correct?

**Comment by Nicogene** [comment]
It is quite strange that `r_ankle_2 ` is missing, it has been substituted by a link with a different name?

That link is involved in these joints: `r_ankle_roll`, `r_foot_front_ft_sensor` and `r_foot_rear_ft_sensor`.

If I understood correctly this PR should just update some stls, but seems that something went wrong in the export of the simmechanics xml

**Comment by mfussi66** [comment]
> It is quite strange that `r_ankle_2 ` is missing, it has been substituted by a link with a different name?

It seems like it belong to a now suppressed test group of links: https://github.com/icub-tech-iit/fix/issues/966#issuecomment-925045131
 
> (and why just `r_ankle_2` and not `l_ankle_2`?)

Could it be that the script fails and exits on the first error, which happens to be caused by `r_ankle_2` that is parsed first?

**Comment by Nicogene** [comment]
> Could it be that the script fails and exits on the first error, which happens to be caused by r_ankle_2 that is parsed first?

Yes probably after removing that frame we will have other issues, I suggest to test it locally is quite easy, just follow:

https://github.com/robotology/icub-models-generator/blob/36ca1b948c6b35dd30246145af28176a27e4326d/.github/workflows/ci.yml#L37-L99

**Comment by pattacini** [comment]
Hi @Nicogene 

> It is quite strange that `r_ankle_2 ` is missing, it has been substituted by a link with a different name?

My understanding is that since some time the sole is split in two (a front and a rear part), thus the two distinct frames.

> (and why just `r_ankle_2` and not `l_ankle_2`?)

Maybe the CI stopped before processing the left ankle?

> If I understood correctly this PR should just update some stls, but seems that something went wrong in the export of the simmechanics XML

It indeed remains unclear why the problem with `r_ankle_2` just showed up now.

**Comment by Nicogene** [comment]
> My understanding is that since some time the sole is split in two (a front and a rear part), thus the two distinct frames.

This is how the ft sensor was defined in iCub 2.5 

https://github.com/robotology/icub-models-generator/blob/36ca1b948c6b35dd30246145af28176a27e4326d/simmechanics/data/icub2_5/ICUB_2-5_BB_simmechanics_options.yaml.in#L75

Here instead how they are defined in iCub 3:

https://github.com/robotology/icub-models-generator/blob/36ca1b948c6b35dd30246145af28176a27e4326d/simmechanics/data/icub3/ICUB_3_all_options.yaml#L76-L77

As you can see the `r_ankle_2` has been always involved in iCub 3

**Comment by pattacini** [comment]
So the problem might be that we need the frame, which has been somehow removed then.
@Mick3Lozzo

**Comment by Mick3Lozzo** [comment]
Re-added the frame in both feet @pattacini.

Now we should clarify their placement inside the assembly. 



Probably they should be here ad not inside a suppressed group, but I'll wait for @salvi-mattia, maybe there is a reason.

**Review by Nicogene — APPROVED** [review]
If the model works on gazebo, we can merge it 👍🏻

**Comment by pattacini** [comment]
> If the model works on gazebo, we can merge it 👍🏻

@mfussi66 
The CI now works ok 👍🏻 
Do you have feedback from the test with Gazebo?

**Comment by mfussi66** [comment]
> 
> 
> > If the model works on gazebo, we can merge it 👍🏻
> 
> @mfussi66
> The CI now works ok 👍🏻
> Do you have feedback from the test with Gazebo?

Not yet, as I need to check how to generate it from the proposed model.

**Comment by mfussi66** [comment]
image

Yep it seems to be displayed correctly in gazebo!

**Comment by Nicogene** [comment]
Merged, thanks!

**Pull request merged**
